import { FullEvaluationResult } from '../schemas/evaluation.schema';
import { EvaluationService } from './evaluation.service';

export class ReflectionService {
  /**
   * Audits raw JSON generated by evaluation agents.
   * If parsing fails or fields are missing, sanitizes and injects fallback structure.
   */
  static auditAndSanitizeEvaluationPayload(rawText: string): FullEvaluationResult {
    try {
      // Clean potential JSON markdown fences
      let cleaned = rawText.trim();
      if (cleaned.startsWith('```')) {
        cleaned = cleaned.replace(/^```(json)?\n?/, '').replace(/\n?```$/, '');
      }

      const parsed: FullEvaluationResult = JSON.parse(cleaned);

      // Validate & Recalculate Rubric
      if (parsed.rubric) {
        parsed.rubric = EvaluationService.sanitizeRubric(parsed.rubric);
      } else {
        parsed.rubric = EvaluationService.sanitizeRubric({
          meaning: 75,
          grammar: 75,
          vocabulary: 75,
          naturalness: 75,
          fluency: 75,
          collocation: 75,
          nativeUsage: 75,
          overall: 75
        });
      }

      // Ensure Arrays exist
      if (!Array.isArray(parsed.grammarErrors)) {
        parsed.grammarErrors = [];
      }

      if (!parsed.fluencyDetail) {
        parsed.fluencyDetail = {
          isWordByWordTranslation: false,
          isBookish: false,
          isAwkward: false,
          awkwardPhrases: [],
          nativeAlternatives: [],
          naturalnessScore: parsed.rubric.naturalness
        };
      }

      if (!parsed.teacherFeedback) {
        parsed.teacherFeedback = {
          title: 'Kết quả đánh giá',
          praise: 'Bạn đã nỗ lực hoàn thành câu dịch!',
          constructiveCritique: 'Cần chú ý hơn đến cách dùng từ tự nhiên.',
          pedagogicalExplanation: 'Dịch câu theo cụm từ thay vì dịch từng từ.',
          whenToUse: 'Dùng trong giao tiếp đời thường.',
          whenNotToUse: 'Tránh dùng trong văn bản viết trang trọng.',
          additionalExamples: []
        };
      }

      if (!parsed.betterTranslations) {
        parsed.betterTranslations = {
          best: 'Gợi ý dịch tự nhiên',
          nativeUS: 'American Spoken Option',
          nativeUK: 'British Spoken Option',
          formalBusiness: 'Workplace Option',
          casualFriendly: 'Casual Friendly Option'
        };
      }

      if (!Array.isArray(parsed.targetedPracticeExercises)) {
        parsed.targetedPracticeExercises = [];
      }

      return parsed;
    } catch (error) {
      console.error('Reflection Agent: JSON parsing/validation failed, generating fallback.', error);
      return {
        rubric: EvaluationService.sanitizeRubric({
          meaning: 70,
          grammar: 70,
          vocabulary: 70,
          naturalness: 70,
          fluency: 70,
          collocation: 70,
          nativeUsage: 70,
          overall: 70
        }),
        grammarErrors: [],
        fluencyDetail: {
          isWordByWordTranslation: false,
          isBookish: false,
          isAwkward: false,
          awkwardPhrases: [],
          nativeAlternatives: [],
          naturalnessScore: 70
        },
        teacherFeedback: {
          title: 'Kết quả đánh giá',
          praise: 'Bạn đã hoàn thành câu dịch.',
          constructiveCritique: 'Hãy thử dùng các phrasal verb tự nhiên hơn.',
          pedagogicalExplanation: 'Tập trung vào phản xạ cụm từ thay vì dịch thô.',
          whenToUse: 'Hàng ngày',
          whenNotToUse: 'Trang trọng',
          additionalExamples: []
        },
        betterTranslations: {
          best: 'Natural Spoken English Option',
          nativeUS: 'American Spoken Option',
          nativeUK: 'British Spoken Option',
          formalBusiness: 'Workplace Option',
          casualFriendly: 'Casual Option'
        },
        targetedPracticeExercises: []
      };
    }
  }
}
